server:
  port: 8888

spring:
  http:
      multipart:
        enabled: true
        max-file-size: 3000MB
        max-request-size: 3000MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.102:3306/aqxj?characterEncoding=utf8&useSSL=true&tcpRcvBuf=1024000
    username: root
    password: root
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  activiti:
      check-process-definitions: false
  mvc:
    view:
      prefix: /html/
      suffix: .html

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com:
      jjkj: DEBUG

security:
  basic:
    enabled: false



